add_newline = true
format = "$os$username$hostname$directory$git_branch$git_status$c$rust$golang$nodejs$php$java$kotlin$haskell$python$docker_context$conda\n$character"
palette = "sholtor_dark"

[c]
format = "[[ $symbol( $version) ](fg:colour_blue)]($style)"
style = ""
symbol = " "

[character]
disabled = false
error_symbol = "[❯](fg:red)"
success_symbol = "[❯](fg:green)"
vimcmd_replace_one_symbol = "[❮](fg:purple)"
vimcmd_replace_symbol = "[❮](fg:purple)"
vimcmd_symbol = "[❮](fg:green)"
vimcmd_visual_symbol = "[❮](fg:yellow)"

[conda]
format = "[[ $symbol( $environment) ](fg:#83a598)]($style)"
style = ""

[directory]
format = "[:$path]($style)"
home_symbol = "~"
style = "fg:green"
truncate_to_repo = false
use_os_path_sep = true

[docker_context]
format = "[[ $symbol( $context) ](fg:#83a598)]($style)"
style = ""
symbol = ""

[git_branch]
format = "[[ $symbol $branch ](fg:cyan)]($style)"
style = ""
symbol = ""

[git_status]
format = "[[($all_status$ahead_behind )](fg:cyan)]($style)"
style = ""

[golang]
format = "[[ $symbol( $version) ](fg:colour_go)]($style)"
style = ""
symbol = ""

[haskell]
format = "[[ $symbol( $version) ](fg:colour_blue)]($style)"
style = ""
symbol = ""

[hostname]
format = "[@$hostname$ssh_symbol]($style)"
ssh_only = false
ssh_symbol = ": "
style = "fg:cyan"
trim_at = "."

[java]
format = "[[ $symbol( $version) ](fg:colour_java)]($style)"
style = ""
symbol = " "

[kotlin]
format = "[[ $symbol( $version) ](fg:colour_blue)]($style)"
style = ""
symbol = ""

[kubernetes]
disabled = false
format = "[[ $symbol( $context) ](fg:#326ce5)]($style)"

[nodejs]
format = "[[ $symbol( $version) ](fg:colour_node)]($style)"
style = ""
symbol = ""

[os]
disabled = false
style = "fg:cyan"

[os.symbols]
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = ""
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = "  "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
RockyLinux = " "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
openSUSE = " "

[palettes.sholtor_dark]
colour_aqua = "#689d6a"
colour_bg0 = "#424242"
colour_blue = "#458588"
colour_fg0 = "#ffffff"
colour_fg1 = "#E64747"
colour_folder = "#3EC669"
colour_go = "#7FD5EA"
colour_green = "#98971a"
colour_java = "#E64747"
colour_julia = "#9B6BDF"
colour_lblue = "#43CCEA"
colour_node = "#42E66C"
colour_orange = "#d65d0e"
colour_php = "#4063D9"
colour_purple = "#b16286"
colour_python = "#E4F34A"
colour_red = "#cc241d"
colour_ruby = "#E64747"
colour_ssh = "#43CCEA"
colour_ubuntu = "#EB6536"
colour_yellow = "#d79921"

[php]
format = "[[ $symbol( $version) ](fg:colour_php)]($style)"
style = ""
symbol = ""

[python]
format = "[[ $symbol( $version) ](fg:colour_python)]($style)"
style = ""
symbol = ""

[rust]
format = "[[ $symbol( $version) ](fg:blue)]($style)"
style = ""
symbol = ""

[username]
format = "[ $user]($style)"
show_always = true
style_root = "fg:red bold"
style_user = "fg:cyan bold"
